class Url:
    DOMAIN = 'https://demoqa.com/'

    AUTOMATION_PRACTICE_FORM = DOMAIN + 'automation-practice-form'
    TEXT_BOX = DOMAIN + 'text-box'
    CHECKBOX = DOMAIN + 'checkbox'
    RADIO_BUTTON = DOMAIN + 'radio-button'
    WEBTABLES = DOMAIN + 'webtables'
    BUTTONS = DOMAIN + 'buttons'
    LINKS = DOMAIN + 'links'
    BROKEN = DOMAIN + 'broken'
    UPLOAD_DOWNLOAD = DOMAIN + 'upload-download'
    DYNAMIC_PROPERTIES = DOMAIN + 'dynamic-properties'
    SELECT_MENU = DOMAIN + 'select-menu'
    MODAL_DIALOGS = DOMAIN + 'modal-dialogs'
    DATE_PICKER = DOMAIN + 'date-picker'
    CHECK_BOX = DOMAIN + 'checkbox'